# Generated by Django 3.2.9 on 2021-11-17 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_code",
                    models.CharField(choices=[("pro", "Pro")], max_length=40),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("expired", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="trialrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "membership_code"), name="unique_trial_user_membership"
            ),
        ),
    ]
