# Generated by Django 3.2.9 on 2021-11-12 06:06

from django.db import migrations
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()


def create_default_membership(apps, schema_editor):
    """
    Create a default membership type and memberships for all users using this type.
    """
    MembershipType = apps.get_model("accounts", "MembershipType")
    Membership = apps.get_model("accounts", "Membership")
    membership_type = MembershipType.objects.create(
        name=settings.DEFAULT_MEMBERSHIP_NAME,
        price=settings.DEFAULT_MEMBERSHIP_PRICE,
        code=settings.DEFAULT_MEMBERSHIP_CODE,
    )
    for user in User.objects.filter(is_active=True):
        Membership.objects.create(membership_type=membership_type, user_id=user.pk)


def remove_default_membership(apps, schema_editor):
    MembershipType = apps.get_model("accounts", "MembershipType")
    Membership = apps.get_model("accounts", "Membership")

    try:
        membership_type = MembershipType.objects.get(
            code=settings.DEFAULT_MEMBERSHIP_CODE
        )
    except MembershipType.DoesNotExist:
        membership_type = MembershipType.objects.first()
    if membership_type:
        Membership.objects.filter(membership_type=membership_type).delete()

    membership_type.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_membership_membershiptype"),
    ]

    operations = [
        migrations.RunPython(create_default_membership, remove_default_membership)
    ]
