# Generated by Django 3.2.9 on 2021-11-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0003_create_default_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="group",
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_type",
                to="auth.group",
                verbose_name="Permissions group",
            ),
        ),
    ]
