# Generated by Django 3.2.9 on 2021-11-21 11:19

from django.db import migrations
from django.conf import settings


def create_wallets(apps, schema_editor):
    CreditWallet = apps.get_model("accounts", "CreditWallet")
    user_app_label, user_model = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model)
    for user in User.objects.all():
        wallet = CreditWallet(user=user)
        wallet.full_clean()
        wallet.save()


def delete_wallets(apps, schema_editor):
    CreditWallet = apps.get_model("accounts", "CreditWallet")
    for wallet in CreditWallet.objects.all():
        if len(wallet.credits) > 0:
            raise Exception("Cannot delete non-empty wallet.")
        else:
            CreditWallet.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_creditwallet"),
    ]

    operations = [migrations.RunPython(create_wallets, delete_wallets)]
