# Generated by Django 3.2.9 on 2021-11-12 10:40

from django.db import migrations


def create_groups(apps, schema_editor):
    MembershipType = apps.get_model("accounts", "MembershipType")
    Group = apps.get_model("auth", "group")
    for membership_type in MembershipType.objects.all():
        group = Group.objects.create(name=membership_type.name)
        membership_type.group = group
        membership_type.save()


def delete_groups(apps, schema_editor):
    MembershipType = apps.get_model("accounts", "MembershipType")
    Group = apps.get_model("auth", "group")
    for membership_type in MembershipType.objects.all():
        Group.objects.get(name=membership_type.name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_membershiptype_group"),
    ]

    operations = [migrations.RunPython(create_groups, delete_groups)]
