# Generated by Django 3.2.9 on 2021-11-12 11:35

from django.db import migrations


def add_users_to_group(apps, schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    for membership in Membership.objects.all():
        membership.user.groups.add(membership.membership_type.group)


def remove_users_from_group(apps, schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    for membership in Membership.objects.all():
        membership.user.groups.remove(membership.membership_type.group)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_create_corresponding_groups"),
    ]

    operations = [migrations.RunPython(add_users_to_group, remove_users_from_group)]
